Revert "only call send once per call to process_sending"
This reverts commit 185db9b00287dfa75f16f546504139faf322949c.

The commit was making TLS connection fail with the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xivo_cti/ctiserver.py", line 678, in select_step
    sel_o.process_sending()
  File "/usr/lib/python2.7/dist-packages/xivo_cti/client_connection.py", line 75, in process_sending
    raise socket.error(_errno, string)
error: [Errno 1] _ssl.c:1298: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry